@echo off
set "PATH=C:\opencv\build\x64\vc16\bin;C:\TensorRT\lib;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4\bin;%PATH%"
echo [ATOS] Initializing v2.0 Production Environment...
echo [ATOS] Targeting RTX 5050 Hardware Context...
.\atos_traffic_system.exe
